import { getProject } from '@theatre/core';
import {
  LYRICS, buildTimeline, TOTAL_DURATION, PHOTO_LAYERS, DOODLE_LAYERS,
  DEPTH_TIERS, assetPath, moodAt,
} from './lyrics-data.mjs';
import { initScene, IS_MOBILE } from './scene/scene3d.js';
import { createPhotoSprite, aspectOf } from './scene/photoLayers.js';
import './style.css';

import heartSvg from './doodles/heart.svg?raw';
import sparkleSvg from './doodles/sparkle.svg?raw';
import sparklesSvg from './doodles/sparkles.svg?raw';
import starSvg from './doodles/star.svg?raw';
import xSvg from './doodles/x.svg?raw';

const DOODLE_ICONS = { heart: heartSvg, sparkle: sparkleSvg, sparkles: sparklesSvg, star: starSvg, x: xSvg };

const audio = document.getElementById('track');
const stack = document.getElementById('stack');
const stageEl = document.getElementById('stage');
const progressFill = document.getElementById('progress-fill');
const playBtn = document.getElementById('play-btn');
const finaleEl = document.getElementById('finale');
const finaleFlourish = document.getElementById('finale-flourish');
const introVinyl = document.getElementById('intro-vinyl');
const sceneCanvas = document.getElementById('scene-canvas');
const root = document.documentElement;

introVinyl.innerHTML = '<div class="vinyl-disc"></div>';

// Finale flourish — a couple of the photo cutouts get one last still moment
// scattered around the closing message.
[
  { asset:'rose.png', top:'14%', left:'8%' },
  { asset:'ring.png', top:'20%', left:'auto', right:'10%' },
  { asset:'pearl-necklace.png', top:'68%', left:'10%' },
].forEach(cue => {
  const wrap = document.createElement('div');
  wrap.className = 'finale-photo';
  wrap.style.top = cue.top;
  wrap.style.left = cue.left ?? 'auto';
  if (cue.right) wrap.style.right = cue.right;
  wrap.innerHTML = `<img src="${assetPath(cue.asset)}" alt="" loading="lazy">`;
  finaleFlourish.appendChild(wrap);
});

const TIMELINE = buildTimeline(LYRICS, TOTAL_DURATION);
const scene = initScene(sceneCanvas);

/**
 * Line slots are centered (left:50%) so they need translate(-50%,-50%) to
 * stay anchored.
 */
function applyLineTransform(el, v){
  if (!v) return;
  const x = v.x || 0, y = v.y || 0, scale = v.scale ?? 1, rotate = v.rotate || 0;
  el.style.transform = `translate(calc(-50% + ${x}px), calc(-50% + ${y}px)) scale(${scale}) rotate(${rotate}deg)`;
  el.style.opacity = v.opacity ?? 1;
  if (v.blur !== undefined) el.style.filter = v.blur > 0.05 ? `blur(${v.blur}px)` : 'none';
  if (v.weight !== undefined) el.style.fontVariationSettings = `'wght' ${Math.round(v.weight)}`;
}

/** Fixed on-screen anchor (never under the centered text column) + a
 * Theatre-driven opacity/scale/rotate for a doodle DOM element. */
function buildDoodle(d, idx){
  const wrap = document.createElement('div');
  wrap.className = 'doodle';
  wrap.innerHTML = DOODLE_ICONS[d.icon] || '';
  const side = idx % 2 === 0 ? 'left' : 'right';
  wrap.style[side] = (6 + (idx % 3) * 6) + '%';
  wrap.style.top = (16 + ((idx * 53) % 62)) + '%';
  stageEl.appendChild(wrap);
  return wrap;
}
function applyDoodleTransform(el, v){
  if (!v) return;
  el.style.opacity = v.opacity ?? 0;
  el.style.transform = `scale(${v.scale ?? 1}) rotate(${v.rotate || 0}deg)`;
}

/** Converts a photo layer's authored frustum-fraction x/y + depth-tier
 * screenFrac into a real world-space sprite position/scale, using the
 * camera's *live* fov/aspect/z — this is what keeps a layer visible and
 * correctly sized on any viewport instead of a fixed world-unit guess. */
function applyPhotoTransform(sprite, tier, path, v){
  if (!v) return;
  sprite.visible = v.opacity > 0.01;
  if (!sprite.visible) return;
  const distance = scene.camera.position.z - tier.z;
  const vFov = scene.camera.fov * Math.PI / 180;
  const fullHeight = 2 * Math.tan(vFov / 2) * distance;
  const halfWidth = (fullHeight / 2) * scene.camera.aspect;
  const spriteHeight = tier.screenFrac * fullHeight * (v.scaleMul ?? 1) * (IS_MOBILE ? 0.72 : 1);
  const spriteWidth = spriteHeight * aspectOf(path);
  sprite.position.set(v.x * halfWidth, v.y * (fullHeight / 2), tier.z);
  sprite.scale.set(spriteWidth, spriteHeight, 1);
  sprite.material.opacity = v.opacity ?? 1;
  sprite.material.rotation = ((v.rotate || 0) * Math.PI) / 180;
}

/**
 * Real timing data (word-level, transcription-grounded — see ATTRIBUTION.md)
 * from lyrics-data.mjs. Real choreography (position/opacity/scale/rotate/
 * blur/weight for every line, camera, mood, and every parallax photo/doodle
 * layer) from a genuine Theatre.js sequence in
 * public/assets/theatre-state.json (generated by
 * tools/build-theatre-state.mjs — see that file for why it's generated
 * rather than hand-authored in Theatre.js Studio's visual editor).
 * Rendering here is just: scrub `sheet.sequence.position` to
 * audio.currentTime every frame, and apply whatever values each object's
 * onValuesChange hands back. No custom per-frame motion math lives in this
 * file — word-level kinetic entrance and the sung/unsung sweep are the one
 * deliberate exception, staying outside Theatre.js since they're discrete
 * per-timestamp state, not a continuously tweened value.
 */
async function main(){
  const state = await (await fetch('/assets/theatre-state.json')).json();
  const project = getProject('My Sweetheart', { state });
  const sheet = project.sheet('Lyrics');
  await project.ready;

  const introObj = sheet.object('intro-vinyl', { opacity:0, scale:1 });
  introObj.onValuesChange(v => {
    if (!v) return;
    introVinyl.style.transform = `translate(-50%,-50%) scale(${v.scale})`;
    introVinyl.style.opacity = v.opacity;
  });

  const moodObj = sheet.object('mood', { hue:8, warmth:0.5 });
  moodObj.onValuesChange(v => {
    root.style.setProperty('--mood-hue', v.hue.toFixed(1));
    root.style.setProperty('--mood-warmth', v.warmth.toFixed(2));
    scene.setParticleHue(v.hue);
  });

  const cameraObj = sheet.object('camera', { z:8, fov:45, yaw:0 });
  cameraObj.onValuesChange(v => {
    scene.camera.position.z = v.z;
    scene.camera.position.x = Math.sin(v.yaw) * 1.6;
    scene.camera.fov = v.fov;
    scene.camera.lookAt(0, 0, 0);
    scene.camera.updateProjectionMatrix();
  });

  PHOTO_LAYERS.forEach((layer, idx) => {
    const tier = DEPTH_TIERS[layer.depth];
    const path = assetPath(layer.asset);
    const sprite = createPhotoSprite(path);
    scene.scene.add(sprite);
    const obj = sheet.object(`photo-${idx}`, { opacity:0, scaleMul:1, x:0, y:0, rotate:0 });
    obj.onValuesChange(v => applyPhotoTransform(sprite, tier, path, v));
  });

  DOODLE_LAYERS.forEach((d, idx) => {
    const el = buildDoodle(d, idx);
    const obj = sheet.object(`doodle-${idx}`, { opacity:0, scale:1, rotate:0 });
    obj.onValuesChange(v => applyDoodleTransform(el, v));
  });

  let lineIndex = 0;
  const wordWatchers = [];

  // A randomized subset of emotionally-loaded words gets a warm accent
  // instead of plain ink, re-rolled on every page load.
  const STOP_WORDS = new Set(['the','a','an','of','in','on','with','that','so','just','still','it','by','me','you','i','am','our']);
  const PRIORITY_WORDS = new Set(['sweetheart','love','true','dreaming','dreams','dream','moonlight','whisper','sweetheart?']);
  function randomizeAccents(wordEls){
    for (const wd of wordEls){
      const clean = wd.el.textContent.toLowerCase().replace(/[.,!?"']/g, '');
      if (STOP_WORDS.has(clean)) continue;
      const chance = PRIORITY_WORDS.has(clean) ? 0.8 : 0.28;
      wd.el.classList.toggle('word-special', Math.random() < chance);
    }
  }

  TIMELINE.forEach((entry) => {
    if (entry.type === 'gap') return;

    const i = lineIndex++;
    const el = document.createElement('div');
    el.className = 'line-slot';

    if (entry.section){
      const tag = document.createElement('div');
      tag.className = 'section-tag';
      tag.textContent = entry.section;
      el.appendChild(tag);
    }

    const lineEl = document.createElement('div');
    lineEl.className = 'lyric-line' + (entry.type === 'spoken' ? ' spoken' : '');
    const wordEls = [];
    (entry.words || []).forEach((w, wi) => {
      const span = document.createElement('span');
      span.className = 'word';
      if (w.w.toLowerCase().replace(/[.,!?"']/g, '') === 'sweetheart') span.classList.add('word-script');
      span.textContent = w.w;
      lineEl.appendChild(span);
      if (wi < entry.words.length - 1) lineEl.appendChild(document.createTextNode(' '));
      wordEls.push({ el: span, start: w.s, end: w.e });
    });
    el.appendChild(lineEl);
    stack.appendChild(el);

    const lineObj = sheet.object(`line-${i}`, { x:0, y:0, opacity:1, scale:1, rotate:0, blur:0, weight:550 });
    lineObj.onValuesChange(v => applyLineTransform(el, v));

    randomizeAccents(wordEls);
    wordWatchers.push({ start: entry.start, end: entry.end, words: wordEls });
  });

  // ------------------------------------------------------------------
  // Word-by-word highlight + kinetic entrance — a discrete state per real
  // timestamp, not a tween, so it stays plain per-frame comparison rather
  // than a Theatre.js track (see main() doc comment above).
  // ------------------------------------------------------------------
  const WORD_LEAD = 0.55;
  function renderWords(t){
    for (const line of wordWatchers){
      if (t < line.start - 3 || t > line.end + 3) continue;
      for (const wd of line.words){
        const isNow = t >= wd.start && t < wd.end;
        const isSung = t >= wd.end;
        wd.el.classList.toggle('is-now', isNow);
        wd.el.classList.toggle('is-sung', isSung && !isNow);
        wd.el.classList.toggle('word-entered', t >= wd.start - WORD_LEAD);
      }
    }
  }

  let rafId = null;
  let lastT = performance.now();
  function frame(now){
    const dt = Math.min((now - lastT) / 1000, 0.1);
    lastT = now;
    const t = audio.currentTime;
    sheet.sequence.position = t;
    renderWords(t);
    progressFill.style.width = (t / TOTAL_DURATION * 100).toFixed(2) + '%';
    scene.render(dt);
    rafId = requestAnimationFrame(frame);
  }

  function togglePlay(){
    if (audio.paused){
      finaleEl.classList.remove('visible');
      stageEl.classList.remove('hidden');
      if (audio.ended || audio.currentTime >= TOTAL_DURATION - 0.05) audio.currentTime = 0;
      audio.play();
      playBtn.classList.add('is-playing');
      lastT = performance.now();
      if (!rafId) rafId = requestAnimationFrame(frame);
    } else {
      audio.pause();
      playBtn.classList.remove('is-playing');
    }
  }
  playBtn.addEventListener('click', togglePlay);

  audio.addEventListener('ended', () => {
    playBtn.classList.remove('is-playing');
    stageEl.classList.add('hidden');
    finaleEl.classList.add('visible');
    if (rafId){ cancelAnimationFrame(rafId); rafId = null; }
  });

  // Render the very first frame (t=0) immediately so the page isn't blank
  // before the visitor presses play.
  sheet.sequence.position = 0;
  renderWords(0);
  const initialMood = moodAt(0);
  root.style.setProperty('--mood-hue', initialMood.hue);
  root.style.setProperty('--mood-warmth', initialMood.warmth);
  scene.setParticleHue(initialMood.hue);
  scene.render(0);
}

main().catch(err => console.error('Theatre.js/Three.js init failed:', err));
